### ISSUE TITLE
Cannot run the experiment c3p with lambda 2.00e-05

### ISSUE THREAD

**Issue by ausumezbas** [mauriceqch/pcc_geo_cnn_v2#4]
Dear Maurice Quach,

Thank you for making this repository available. I'm working on running ev_run_experiments.py following the steps described in the Readme file and generate all the results for the 4 test point clouds at the bottom of ev_experiment.yml

I was able to run the complete training script and I see models generated for all configurations. The training logs also look reasonable.

I am also able to generate the test results for c1 and c2 configurations, but I get stuck at the compress_octree stage when trying to process c3p with lambda 2.00e-05 (other lambdas for c3p also work okay).

I have attached the relevant compress.log file. It looks like an index has 0-value, and one thing that struck me as different in this log versus the other ones that completed successfully is the message that says: 
Fixed threshold 128/256 with 0/2121 points (ratio 0.00)

The ratios in the successfully completed tests are all nonzero. 

I have tried to trace this problem down a bit, and it looks like line 29 in model_opt.py:
half_pa = np.argwhere(x_hat > thresholds[half_thr]).astype('float32')

returns an empty half_pa for all blocks for the soldier_vox10 input. It looks like all the values in x_hat are smaller than the half threshold value.

I was wondering if I'm missing a step here, or doing something wrong? Any help you can provide would be greatly appreciated. I can provide more information and/or log files if that would be helpful in pinpointing what might be going wrong.

Many thanks for your time.
Anil
[compress_error.log](https://github.com/mauriceqch/pcc_geo_cnn_v2/files/6071113/compress_error.log)

**Comment by mauriceqch** [comment]
Hi @ausumezbas,

Thank you for your interest!

The logfile you attached indicates that the neural network predictions seem seriously wrong...
As you've observed, all values seem to be smaller than 0.5 which is not normal.
Attached is the logfile of a normal run for the c3p lmbda 2.00e-05 configuration.
[compress.log](https://github.com/mauriceqch/pcc_geo_cnn_v2/files/6071905/compress.log)

Since you indicate that other lambdas are working fine, perhaps something went wrong with the model ?
The full experimental data is available [here](https://drive.google.com/file/d/18uHmr0ZpgFLeL9Y5TUFTsQkRfz4XpQdJ/view?usp=sharing) and includes trained models and resulting point clouds.

Can you compare the c3p 2.00e-05 model in the data above with yours in tensorboard to see if something went differently during training ?

**Comment by ausumezbas** [comment]
Hi again,

I apologize for the late response, this was indeed an external issue during training, and simply re-running the process resolved the issue. 

Thanks for your help!

**Comment by mauriceqch** [comment]
Hi,

No problem, happy to know that you resolved the issue! Wish you good luck for your experiments!
